//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITEvents.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int ID_Activity { get; set; }
        public string EventName { get; set; }
        public string Activity_1 { get; set; }
        public string Activity_2 { get; set; }
        public string Activity_3 { get; set; }
        public Nullable<int> DAY_1 { get; set; }
        public Nullable<int> DAY_2 { get; set; }
        public Nullable<int> DAY_3 { get; set; }
        public Nullable<System.TimeSpan> TimeStart_1 { get; set; }
        public Nullable<System.TimeSpan> TimeStart_2 { get; set; }
        public Nullable<System.TimeSpan> TimeStart_3 { get; set; }
        public string Moderator_1 { get; set; }
        public string Moderator_2 { get; set; }
        public string Moderator_3 { get; set; }
        public string Jury_1_1 { get; set; }
        public string Jury_1_2 { get; set; }
        public string Jury_1_3 { get; set; }
        public string Jury_2_1 { get; set; }
        public string Jury_2_2 { get; set; }
        public string Jury_2_3 { get; set; }
        public string Jury_3_1 { get; set; }
        public string Jury_3_2 { get; set; }
        public string Jury_3_3 { get; set; }
        public string Jury_4_1 { get; set; }
        public string Jury_4_2 { get; set; }
        public string Jury_4_3 { get; set; }
        public string Jury_5_1 { get; set; }
        public string Jury_5_2 { get; set; }
        public string Jury_5_3 { get; set; }
        public string Winner { get; set; }
    
        public virtual Events Events { get; set; }
    }
}
