//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITEvents.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public int ID_Country { get; set; }
        public string CountryName { get; set; }
        public string CountryNameEn { get; set; }
        public string CodeCountry { get; set; }
    
        public virtual City City { get; set; }
    }
}
