//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITEvents.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        public int ID_Events { get; set; }
        public string Events1 { get; set; }
        public string DATE { get; set; }
        public Nullable<int> DAYS { get; set; }
        public Nullable<int> ID_City { get; set; }
        public string Direction { get; set; }
        public Nullable<int> ID_Direction { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual City City { get; set; }
        public virtual Direction Direction1 { get; set; }
        public virtual Organizer Organizer { get; set; }

		public string ImgPathJpg
		{
			get
			{
				var path = "pack://application:,,,/Resources/" + this.ID_Events + ".jpg";
				return path;
			}
		}
	}
}
